---
- name: User Configuration
  hosts: all
  tags:
    - user
  tasks:
    - name: setup authorized_keys
      authorized_key:
        user: ubuntu
        key: "{{item}}"
      loop: "{{authorized_keys}}"

- name: User Configuration
  hosts: all
  tags:
    - system
  tasks:
    - name: update all software (apt)
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 86400 #One day
        autoremove: yes
      register: update_all_software_apt
      until: update_all_software_apt
      retries: 3
      #setup reboot?

- name: Docker Configuration
  hosts: all
  tags:
    - docker
  roles:
    - geerlingguy.docker
    - nvidia.nvidia_driver
    - nvidia.nvidia_docker
  post_tasks:
    - name: Docker-compose bash autocomplete
      get_url:
        url: https://raw.githubusercontent.com/docker/compose/1.24.0/contrib/completion/bash/docker-compose
        dest: /etc/bash_completion.d/docker-compose
        mode: 0644
